export const chapters = [
	{
		chapter: 'Synchronicity',
		parts: [
			{
				title: 'The Penrose',
				entries: [
					{ title: 'Penrose-Type Vessel Field Operations Manual', place: 'Stern Hall' },
					{ title: 'Smeared Diary Page', place: 'Personnel' },
				],
			},
			{
				title: 'Reeducation',
				entries: [
					{ title: 'Welcome to S-23 Sierpinski', place: 'Surface Access' },
					{ title: 'The Rule of Six', place: 'Corridor' },
					{ title: 'Keep Records!', place: 'Staff Room' },
					{ title: 'No running in the hallways!', place: 'Class 4B' },
					{ title: 'Memorandum: Wall Safe Codes', place: 'Staff Room' },
					{ title: 'Service Request Form F-29', place: 'Staff Room' },
					{ title: 'Mond&Töchter High-Security Wall Safe (Numeric)', place: 'Library' },
					{ title: "Isa's Note", place: 'Library' },
					{ title: 'Dictionary', place: 'Library' },
				],
			},
			{
				title: 'Workers',
				entries: [
					{ title: 'Scrawled Note', place: 'A61' },
					{ title: "Alina's Diary", place: 'A61' },
					{ title: 'Diary', place: 'A64' },
					{ title: 'Interrogation Report', place: 'Office' },
					{ title: 'Wunderwaffen', place: 'Office' },
					{ title: 'Service Request Form R-90', place: 'Pantry' },
					{ title: 'Service Request Form F-29 (2)', place: 'Block A6' },
					{ title: 'About the Administrator', place: 'Rationing Office' },
					{ title: 'Search Protocol', place: 'Registry' },
					{ title: 'Frequencies', place: 'Interrogation' },
					{ title: 'To Radio Officer Yeong, Station 6', place: 'Rotfront Station 06' },
				],
			},
			{
				title: 'Hospital',
				entries: [
					{ title: "Alina's Diary (2)", place: 'ICU 01' },
					{ title: 'Patient EULR-S2321', place: 'ICU 01' },
					{ title: 'Proper Disposal of Corpses', place: 'Incinerator' },
					{ title: 'Flood Drainage System Malfunction', place: 'Pump Room' },
					{ title: 'Reservoir Drainage Instructions', place: 'Pump Room' },
					{ title: 'Personal Grievance Form P-14', place: 'Vent Room' },
					{ title: 'Quick-Curing Construction Foam', place: 'Exam Room' },
				],
			},
			{
				title: 'Protektors',
				entries: [
					{ title: 'Angry Note', place: 'STCR Dorm(B6)' },
					{ title: 'Replika Overview: STAR', place: 'Cleaning Room' },
					{ title: 'Buyan', place: 'STCR Dorm' },
					{ title: 'Operational Procedures: Control', place: 'Service Tunnel' },
					{ title: 'Memorandum: Lighting Malfunctions', place: 'Cleaning Room Hallway' },
					{ title: 'Replika Overview: ARAR', place: 'ARAR Dorm' },
					{ title: 'Heimat', place: 'STAR Dorm' },
					{ title: 'Order No. S23-90A3C28F97', place: 'Dining Room' },
					{ title: 'Kitezh', place: 'Dining Room' },
					{ title: 'Replika Known Issues, Part III', place: 'FKLR Office' },
					{ title: 'Replika Overview: FKLR', place: 'FKLR Study' },
					{ title: "Falke's Diary", place: 'FLKR Bedroom' },
					{ title: 'Replika Overview: ADLR', place: 'ADLR Bedroom' },
					{ title: 'Replika Overview: EULR', place: 'Piano Room' },
					{ title: 'Vineta', place: 'Protektor Archive' },
					{ title: 'Kolibri in the Management Office', place: 'Protektor Archive' },
					{ title: 'Replika Known Issues, Part II', place: 'Workshop' },
					{ title: 'Replika Known Issues, Part I', place: 'KLBR Study' },
					{ title: 'Replika Overview: KLBR', place: 'KLBR Study' },
					{ title: "Kolibri's Note", place: 'KLBR Study' },
					{ title: 'Rotfront', place: 'Flood Overflow' },
					{ title: "Adler's Diary", place: 'ADLR Study' },
					{ title: 'Replika Overview: LSTR', place: 'ADLR Study' },
					{ title: 'Replika Overview: MNHR', place: 'Library' },
					{ title: 'Replika Known Issues, Part IV', place: 'Library' },
					{ title: 'Shrine Diary', place: 'ADLR Study' },
				],
			},
		],
	},
	{
		chapter: 'Liminality',
		parts: [
			{
				title: 'Excavation',
				entries: [
					{ title: 'Monofilament Fiber', place: 'Monowire' },
					{ title: "Alina's Diary (3)", place: 'Mining Station' },
					{ title: 'The Twin Suns', place: 'Shore of Oblivion' },
					{ title: 'Black Stars', place: 'Shore of Oblivion' },
					{ title: 'Tears Unshed', place: 'Shore of Oblivion' },
					{ title: 'Sorts of Death', place: 'Shore of Oblivion' },
					{ title: 'Sorts of Death (2)', place: 'Shore of Oblivion' },
					{ title: 'And a Star Fell', place: 'Shore of Oblivion' },
					{ title: 'A Sea of Flesh', place: 'Shore of Oblivion' },
				],
			},
			{
				title: 'Nowhere',
				entries: [
					{ title: 'Offerings', place: 'Shrine Room' },
					{ title: 'Warnings', place: 'Nursery' },
					{ title: 'The Dreamer', place: 'Falke' },
					{ title: "Alina's Diary (4)", place: 'Lamp Room' },
					{ title: 'Leave', place: 'Classroom' },
					{ title: "The Empress' Hand", place: 'Chapel' },
				],
			},
			{
				title: 'Memory',
				entries: [
					{ title: 'Penrose emergency procedures appendix H', place: 'Medical' },
					{ title: 'Penrose Briefing: Phase II', place: 'Medical' },
					{ title: 'Scheduled Maintenance Checklist', place: 'Stern Hall' },
					{ title: 'Operation Penrose', place: 'Stern Observatory' },
					{ title: 'Replika Known Issues, Penrose Program', place: 'Mess Hall' },
					{ title: "Ariane's Notes", place: 'Storage' },
					{ title: 'Smeared Diary Page (2)', place: 'Personnel (Wrecked)' },
					{ title: 'Unnamed Note', place: 'Stern Hall (Wrecked)' },
					{ title: 'Unnamed Note (2)', place: 'Stern Hall (Wrecked)' },
					{ title: 'Together we will be eternal', place: 'Shore of Oblivion' },
					{ title: 'An ocean of memories', place: 'Shore of Oblivion' },
					{ title: 'Great holes secretly are digged', place: 'Shore of Oblivion' },
					{ title: 'kill me', place: 'Shore of Oblivion' },
				],
			},
		],
	},
	{
		chapter: 'Gestaltzerfall',
		parts: [
			{
				title: 'Rotfront',
				entries: [
					{ title: 'Blockwart', place: 'Hallway' },
					{ title: 'Stolen Document', place: 'Dark Apartment' },
					{ title: 'Message Inbox', place: 'Blockwart Office' },
					{ title: "Teacher's Evaluation: Ariane Yeong", place: 'Hospital Room' },
					{ title: 'Mondfest celebrations canceled over safety concerns', place: 'Apartment' },
					{ title: 'The Red Eye', place: 'Alley' },
					{ title: 'Reunification', place: 'Apartment' },
					{ title: 'Bioresonance Technology and its Limitations', place: 'Butterfly Room' },
					{ title: 'Medical Database', place: 'Blockwart Office' },
					{ title: 'Song of the Gods', place: 'Backroom' },
					{ title: 'Prometheus', place: 'Book Store' },
					{ title: 'Resonant Phenomena', place: 'Book Store' },
					{ title: 'Dream Diary', place: 'Meat Room' },
					{ title: "People's Army, 5th Vinetan Infantry Division, Unit 12", place: 'Photo Store' },
					{ title: 'Leaving', place: 'Packstation' },
				],
			},
			{
				title: 'End',
				entries: [
					{ title: 'Workforce assignment for Yeong, Ariane', place: 'Home' },
					{ title: "Auntie's Note", place: 'Home' },
					{ title: 'Letter from Mother', place: 'Home' },
					{ title: "Adler's Note", place: 'Falke Hall' },
					{ title: 'A Red Dream', place: 'Falke Hall' },
					{ title: 'STOP', place: 'Falke Hall' },
					{ title: "Falke's Memory", place: 'Falke Hall' },
					{ title: 'Excavation Team C', place: 'ADLR Study' },
					{ title: "Adler's Diary (Hidden Top)", place: 'ADLR Study' },
					{ title: "Adler's Diary (Hidden Right)", place: 'ADLR Study' },
					{ title: 'Cycle 225', place: 'Upper Gallery' },
					{ title: 'Penrose Briefing: Phase III', place: 'Medical' },
					{ title: 'Cycle 1294', place: 'Reaktor' },
					{ title: 'Cycle 5309', place: 'Stern Hall' },
				],
			},
		],
	},
];
